blank_issues_enabled: false
contact_links:
  - name: Join the DVT Discord
    url: https://discord.gg/UjQcxJXAQp
    about: Need help? Have questions? Join the DVT community on Discord.
  - name: DVT on PyPI
    url: https://pypi.org/project/dvt-core/
    about: Download the latest version of DVT from PyPI.
